version: 2
jobs:
  build:
    docker:
      # specify the version here
      - image: circleci/elixir:1.7

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo/adventofcode
    steps:
      - checkout:
          path: ~/repo

      # specify any bash command here prefixed with `run: `
      - run: mix deps.get
      - run: mix dialyzer
      - run: mix test
