defmodule Aoc2025.Day07.Test do
  use ExUnit.Case

  @example "
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
  "
  test "solve" do
    assert Aoc2025.Day07.solve1(@example) == 21
    # {:ok, text} = File.read("test/input07")
    # assert Aoc2025.Day07.solve1(text) == 1555
  end

  test "solve2" do
    assert Aoc2025.Day07.solve2(@example) == 40
    # {:ok, text} = File.read("test/input07")
    # assert Aoc2025.Day07.solve2(text) == 12_895_232_295_789
  end
end
